#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Create the standalone dashboard project structure.

Run once from anywhere:
    python scripts/setup_folders.py

Creates (at the project root, regardless of current directory), one estate
subfolder per tab — data is organized by tab first, then estate:
    data/Agronomic Assessment/Rembau/   data/Agronomic Assessment/Setiawan/   data/Agronomic Assessment/Serdang/
    data/Bunch Development/Rembau/      data/Bunch Development/Setiawan/      data/Bunch Development/Serdang/
    data/Yield Map/Rembau/              data/Yield Map/Setiawan/              data/Yield Map/Serdang/
    outputs/

Then COPY each flight folder AND its matching _frame_metadata.csv into the
correct estate folder under Agronomic Assessment, e.g.
    data/Agronomic Assessment/Serdang/DJI_20260113101712_0103_D/
    data/Agronomic Assessment/Serdang/DJI_20260113101712_0103_D_frame_metadata.csv
Copying (not just referencing) keeps this dashboard fully self-contained.
(You may add month subfolders if you like; month is derived from the flight date.)

Bunch Development / Yield Map are still mock-generated by the dashboard for
now — their estate folders are scaffolded here so real data has a home once
that's wired up (see core/dashboard_data.py's mock_bunch()/mock_yield()).
"""

import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ESTATES = ["Rembau", "Setiawan", "Serdang"]  # add/rename freely
TABS = ["Agronomic Assessment", "Bunch Development", "Yield Map"]


def main():
    for tab in TABS:
        for e in ESTATES:
            os.makedirs(os.path.join(PROJECT_ROOT, "data", tab, e), exist_ok=True)
    os.makedirs(os.path.join(PROJECT_ROOT, "outputs"), exist_ok=True)
    print("Created:")
    for tab in TABS:
        for e in ESTATES:
            print(f"  data/{tab}/{e}/")
    print("  outputs/")
    print("\nNext: move each DJI_* folder + its _frame_metadata.csv into the "
          "matching data/Agronomic Assessment/<estate>/ folder, then run "
          "build_wc1_assessment.py")


if __name__ == "__main__":
    main()
